version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: airflow_postgres
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  airflow-init:
    build: .
    env_file:
      - .env
    container_name: airflow_init
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW_UID: 50000
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./spark/jars:/opt/airflow/jars
      - ./jars:/opt/airflow/jars
      - ./data:/opt/airflow/data
      - ./plugins:/opt/airflow/plugins
      - ./logs:/opt/airflow/logs
      - ./powerbi:/opt/airflow/powerbi
    command: >
      bash -c "
      airflow db init &&
      airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@example.com --skip-redirect
      "
    restart: "no"

  airflow-webserver:
    build: .
    env_file:
      - .env  
    container_name: airflow_webserver
    depends_on:
      - postgres
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__WEBSERVER__SECRET_KEY: airflowsecret
      AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth
      AIRFLOW_UID: 50000
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./spark:/opt/airflow/spark
      - ./spark/jars:/opt/airflow/jars
      - ./data:/opt/airflow/data
      - ./plugins:/opt/airflow/plugins
      - ./logs:/opt/airflow/logs
      - ./powerbi:/opt/airflow/powerbi
    ports:
      - "8080:8080"
    command: airflow webserver

  airflow-scheduler:
    build: .
    env_file:
      - .env
    container_name: airflow_scheduler
    depends_on:
      - postgres
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW_UID: 50000
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./spark:/opt/airflow/spark
      - ./spark/jars:/opt/airflow/jars
      - ./data:/opt/airflow/data
      - ./plugins:/opt/airflow/plugins
      - ./logs:/opt/airflow/logs
      - ./powerbi:/opt/airflow/powerbi
    command: airflow scheduler

volumes:
  postgres_db:
  logs:
  spark: